version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ContainerizeSolution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  usersapi:
    build: .
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=ContainerizeSolution;User Id=postgres;Password=Aa123456;"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres

volumes:
  postgres-data: